---
- name: "Import Grafana GPG key"
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: "Add Grafana stable repository"
  ansible.builtin.apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
